package chatbidireccional;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Subgrupo 1
 */
public class Client extends javax.swing.JFrame {

    /**
     * Crea una nueva instancia del cliente
     */
    public Client() {
        initComponents();
    }

    private static Socket socket;
    private static BufferedReader entrada;
    private static PrintWriter salida;
    private static String nombreUsuario;

    /**
     * Conecta el socket al servidor
     *
     * @param ip la IP del servidor
     * @param port el puerto de conexión
     */
    private static void ConnectSocket(String ip, Integer port) {
        try {
            socket = new Socket(ip, port);
            System.out.println("Conectado al servidor");

            entrada = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            salida = new PrintWriter(socket.getOutputStream(), true);

            startServerListenerThread();
        } catch (IOException e) {
            System.out.println("Error al conectar con el servidor: " + e.getMessage());
        }
    }

    /**
     * Inicia un hilo para escuchar mensajes del servidor
     */
    private static void startServerListenerThread() {
        Thread hilo = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    String mensajeServidor;
                    while ((mensajeServidor = entrada.readLine()) != null) {
                        System.out.println(mensajeServidor);
                        chat_textarea.append(mensajeServidor + "\n");
                        if ("Chat cerrado".equals(mensajeServidor)) {
                            break;
                        }
                    }
                } catch (IOException e) {
                    System.out.println("Error en la conexión: " + e.getMessage());
                }
            }
        });

        hilo.start();
    }

    /**
     * Envía el nombre de usuario al servidor
     *
     * @param name el nombre de usuario
     */
    private static void SendName(String name) {
        salida.println(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        ip_label = new javax.swing.JLabel();
        port_label = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        ip_textfield = new javax.swing.JTextField();
        port_textfield = new javax.swing.JTextField();
        name_textfield = new javax.swing.JTextField();
        cancel_button = new javax.swing.JButton();
        accept_button = new javax.swing.JButton();
        chat_scrollpane = new javax.swing.JScrollPane();
        chat_textarea = new javax.swing.JTextArea();
        message_textfield = new javax.swing.JTextField();
        send_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ip_label.setText("IP del servidor:");

        port_label.setText("Puerto de la conexión:");

        name_label.setText("Escriba su nombre:");

        port_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                port_textfieldActionPerformed(evt);
            }
        });

        cancel_button.setText("Cancelar");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        accept_button.setText("Aceptar");
        accept_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept_buttonActionPerformed(evt);
            }
        });

        chat_textarea.setEditable(false);
        chat_textarea.setColumns(20);
        chat_textarea.setRows(5);
        chat_scrollpane.setViewportView(chat_textarea);

        send_button.setText("Enviar");
        send_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chat_scrollpane)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_label)
                            .addComponent(ip_label)
                            .addComponent(port_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(port_textfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cancel_button)
                                .addGap(18, 18, 18)
                                .addComponent(accept_button))
                            .addComponent(ip_textfield, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name_textfield)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(message_textfield)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(send_button)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ip_label)
                    .addComponent(ip_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(port_label)
                    .addComponent(port_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_label)
                    .addComponent(name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_button)
                    .addComponent(accept_button))
                .addGap(18, 18, 18)
                .addComponent(chat_scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(message_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send_button))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void port_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_port_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_port_textfieldActionPerformed

    /**
     * Acción al presionar el botón Aceptar
     *
     * @param evt evento disparado
     */
    private void accept_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept_buttonActionPerformed
        String ip = ip_textfield.getText();
        Integer port = Integer.parseInt(port_textfield.getText());
        nombreUsuario = name_textfield.getText();

        ConnectSocket(ip, port);
        SendName(nombreUsuario);
    }//GEN-LAST:event_accept_buttonActionPerformed

    /**
     * Acción al presionar el botón Enviar
     *
     * @param evt evento disparado
     */
    private void send_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_buttonActionPerformed
        String mensaje = message_textfield.getText();

        if ("chao".equals(mensaje) || "Chao".equals(mensaje)) {
            try {
                salida.println(mensaje);
                socket.close();

                dispose();
            } catch (IOException ex) {
                Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        salida.println(mensaje);
        chat_textarea.append(nombreUsuario + ": " + mensaje + "\n");
        message_textfield.setText("");
    }//GEN-LAST:event_send_buttonActionPerformed

    /**
     * Acción al presionar el botón Cancelar
     *
     * @param evt evento disparado
     */
    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        try {
            socket.close();

            dispose();
        } catch (IOException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancel_buttonActionPerformed

    /**
     * Punto de entrada de la aplicación
     *
     * @param args argumentos de línea de comandos
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept_button;
    private javax.swing.JButton cancel_button;
    private javax.swing.JScrollPane chat_scrollpane;
    private static javax.swing.JTextArea chat_textarea;
    private javax.swing.JLabel ip_label;
    private javax.swing.JTextField ip_textfield;
    private javax.swing.JTextField message_textfield;
    private javax.swing.JLabel name_label;
    private static javax.swing.JTextField name_textfield;
    private javax.swing.JLabel port_label;
    private javax.swing.JTextField port_textfield;
    private javax.swing.JButton send_button;
    // End of variables declaration//GEN-END:variables
}
